steps:
# Run unit tests
- name: 'python:3.7-slim'
  id: Test
  entrypoint: /bin/sh
  args:
  - -c
  - 'pip install flask && python test_app.py -v'

# Build using Kaniko
- name: 'gcr.io/kaniko-project/executor:latest'
  id: Build
  args:
    - --destination=us-west1-docker.pkg.dev/$PROJECT_ID/my-repository/hello-cloudbuild:$SHORT_SHA
    - --dockerfile=./Dockerfile
    - --context=.

# No push step needed; Kaniko pushes automatically

options:
  logging: CLOUD_LOGGING_ONLY
