steps:
# -----------------------------------------------------------
# 1. Run Unit Tests
# -----------------------------------------------------------
- name: "python:3.7-slim"
  id: Test
  entrypoint: /bin/sh
  args:
    - -c
    - |
      pip install flask
      python test_app.py -v

# -----------------------------------------------------------
# 2. Build Image Using Kaniko
# -----------------------------------------------------------
- name: "gcr.io/kaniko-project/executor:latest"
  id: Build
  args:
    - --destination=us-west1-docker.pkg.dev/$PROJECT_ID/my-repository/hello-cloudbuild:$SHORT_SHA
    - --dockerfile=./Dockerfile
    - --context=.

# -----------------------------------------------------------
# 3. CD Step - Push commit to candidate branch of hello-cloudbuild-env
# -----------------------------------------------------------
- name: "gcr.io/cloud-builders/git"
  id: Deploy
  entrypoint: bash
  args:
    - -c
    - |
      echo "=== Setting up SSH authentication ==="
      mkdir -p ~/.ssh

      # Load private SSH key from Secret Manager
      gcloud secrets versions access latest --secret=ssh_key_secret > ~/.ssh/id_rsa
      chmod 600 ~/.ssh/id_rsa

      # Load known_hosts
      cp known_hosts.github ~/.ssh/known_hosts

      echo "=== Cloning environment repo ==="
      git clone git@github.com:workjayeshjadhav-rgb/hello-cloudbuild-env.git
      cd hello-cloudbuild-env

      echo "=== Checkout candidate branch ==="
      git checkout candidate

      echo "=== Configure Git identity ==="
      git config user.email "cloudbuild@google.com"
      git config user.name "Cloud Build"

      echo "=== Creating commit for CD trigger ==="
      git commit --allow-empty -m "CD pipeline deployment update"

      echo "=== Pushing to candidate branch ==="
      git push origin candidate

# -----------------------------------------------------------
# Cloud Build Options
# -----------------------------------------------------------
options:
  logging: CLOUD_LOGGING_ONLY

