steps:
  - id: Test
    name: python:3.7-slim
    entrypoint: bash
    args:
      - -c
      - |
        pip install flask
        python -m unittest test_app.py

  - id: Build
    name: gcr.io/kaniko-project/executor:latest
    args:
      - --dockerfile=Dockerfile
      - --context=.
      - --destination=us-west1-docker.pkg.dev/$PROJECT_ID/my-repository/hello-cloudbuild:$SHORT_SHA

  - id: Deploy
    name: gcr.io/cloud-builders/git
    entrypoint: bash
    args:
      - -c
      - |
        echo "=== Setting up SSH authentication ==="
        mkdir -p ~/.ssh

        gcloud secrets versions access latest --secret=ssh_key_secret > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

        cp known_hosts.github ~/.ssh/known_hosts
        chmod 600 ~/.ssh/known_hosts

        echo "=== Cloning environment repo ==="
        rm -rf hello-cloudbuild-env || true
        GIT_SSH_COMMAND="ssh -o StrictHostKeyChecking=yes" \
          git clone git@github.com:workjayeshjadhav-rgb/hello-cloudbuild-env.git

        cd hello-cloudbuild-env

        echo "=== Checkout candidate branch ==="
        git checkout candidate || git checkout -b candidate

        echo "=== Configure Git identity ==="
        git config user.email "cloudbuild@google.com"
        git config user.name "Cloud Build"

        echo "=== Creating commit for CD trigger ==="
        git commit --allow-empty -m "CD pipeline deployment update"

        echo "=== Pushing to candidate ==="
        GIT_SSH_COMMAND="ssh -o StrictHostKeyChecking=yes" \
          git push origin candidate

images:
  - us-west1-docker.pkg.dev/$PROJECT_ID/my-repository/hello-cloudbuild:$SHORT_SHA
